benchmarks:
  - name: PrecisionAtK
    module: benchmarks.precision
    params:
      k_values: [1, 5, 10]

  - name: GlobalSeparationRate
    module: benchmarks.gsr
    params:
      min_class_size: 2
      epsilon: 1.0e-9
      
  - name: FValueBenchmark
    module: benchmarks.f_value
    params:
      min_class_size: 2

  - name: CSCFBenchmark
    module: benchmarks.cscf
    params:
      min_class_size: 2

  - name: ClusteringPurity
    module: benchmarks.clustering
    params:
      umap_n_components: 2
      hdbscan_min_cluster_size: 5
      use_distance_matrix_for_umap: true
      umap_metric: precomputed
      hdbscan_metric: euclidean

  - name: PerceptualAlignment
    module: benchmarks.perceptual
    params:
      probe_consistency_threshold: 0.7
      bootstrap_ci: true
      n_bootstraps: 100

  - name: ClassSeparationRatio
    module: benchmarks.csr
    params:
      min_class_size: 2
      epsilon: 1.0e-9

  - name: ClassificationBenchmark
    module: benchmarks.classification
    params:
      n_splits: 5
      random_state: 42
      classifiers: [knn, rf, mlp]
      eval_metrics: [accuracy]
      top_k: 5
      classifier_params:
        knn:
          n_neighbors: [3, 10, 30]
          n_jobs: [-1]
        rf:
          max_depth: [10, 15, 20]
          random_state: 42
          n_jobs: [-1]
        mlp:
          alpha: [0.1, 0.01, 0.001]
          random_state: 42
          max_iter: 500
          batch_size: auto