
project_root: "."
results_dir: "d:/data2/vocsim/results/paper_avian"
output_tables_dir: "d:/data2/vocsim/paper_outputs/avian_tables_generated"
features_dir: "d:/data2/vocsim/features/paper_avian"
models_dir: &models_output_dir "d:/data2/vocsim/avian_perception_models"
run_id: "avian_scoped_${now:%Y%m%d_%H%M%S}"
force_cpu: false
target_sample_rate: 16000
feature_chunk_size_gb: 3  
logging:
  level: INFO

dataset:
  id: anonymous-submission000/vocsim-applications-avian-perception
  subset: null
  split: train
  subsets_to_run: [avian_perception]

definitions:
  vae_trainer_def: &vae_trainer_def
    name: PaperVAETrainer
    module: reproducibility.trainers.vae
    params:
      z_dim: 32
      learning_rate: 0.001
      model_precision: 10.0
      vae_frontend_params: &vae_frontend_params
        target_sr: 16000
        n_fft: 512
        hop_length: 256
        win_length: 512
        window_fn_str: "hann"
        spec_height: 128
        spec_width: 128
        window_overlap: 0.5
  vae_model_def: &vae_model_def
    name: VariationalAutoencoder
    module: reproducibility.models.vae
    params:
      z_dim: 32
      model_precision: 10.0
  vae_loop_params: &vae_loop_params
    num_epochs: 50
    batch_size: 64
    save_frequency_epochs: 10
    test_frequency: 10
  ae_trainer_def: &ae_trainer_def
    name: PaperAutoencoderTrainer
    module: reproducibility.trainers.autoencoder
    params:
      learning_rate: 0.0003
      regularization_weight: 0.01
  ae_model_def: &ae_model_def
    name: Autoencoder
    module: reproducibility.models.autoencoder
    params:
      bottleneck_dim: 256
      audio_config: &ae_audio_config
        sr: 16000
        n_mels: 128
        nfft: 2048
        fmin: 100.0
        fmax: 8000.0
      dimensions: &ae_dimensions
        nfft: 2048
        max_spec_width: 512
  ae_loop_params: &ae_loop_params
    num_epochs: 50
    batch_size: 128
    early_stopping_patience: 10
    mixed_precision: true
    save_frequency_epochs: 10
  vae_extractor_params: &vae_extractor_params
    <<: *vae_frontend_params
  ae_extractor_params: &ae_extractor_params
    audio_config: *ae_audio_config
    dimensions: *ae_dimensions
    bottleneck_dim: 256

train: 

  - trainer: *vae_trainer_def
    model: *vae_model_def
    train_on_subset: "all"
    <<: *vae_loop_params 

  - trainer: *ae_trainer_def
    model: *ae_model_def
    train_on_subset: "all"
    <<: *ae_loop_params

feature_extractors: 

  - name: PaperVAEExtractor_all
    module: reproducibility.features.vae
    class: PaperVAEExtractor
    params:
      base_models_dir: *models_output_dir
      model_scope: "all"
      <<: *vae_extractor_params
    short_name: CVC
    benchmark_this: true 

  - name: PaperAutoencoderExtractor_all
    module: reproducibility.features.autoencoder
    class: PaperAutoencoderExtractor
    params:
      base_models_dir: *models_output_dir
      model_scope: "all"
      <<: *ae_extractor_params
    short_name: CAC
    benchmark_this: true 

  - name: MelExtractor
    module: features.mel
    params:
      sr: 16000
      n_mels: 80
      n_fft: 2048
      hop_length: 256
      fmin: 100.0
      fmax: 8000.0
      log_scale: true
    short_name: CM
    benchmark_this: true 

  - name: WhisperEncoderExtractor
    module: features.whisper
    params:
      model_id: "openai/whisper-large-v3"
    short_name: EW
    benchmark_this: true 

  - name: WhisperSegExtractor
    module: features.whisperseg.extractor
    params:
      model_path: "d:/data2/vocsim/models/WhisperSegCompatible/whisper-large-v3-ct2"
      output_type: "embedding"
      default_spec_time_step: 0.020
      default_min_frequency: 100.0
      default_num_trials: 1
    short_name: E
    benchmark_this: true 

  - name: WavLMExtractor
    module: features.wavlm
    params:
      model_id: "microsoft/wavlm-large"
    short_name: WLM
    benchmark_this: true 

  - name: Wav2Vec2Extractor
    module: features.wav2vec2
    params:
      model_id: "facebook/wav2vec2-base-960h"
    short_name: CW
    benchmark_this: true 

  - name: CLAPExtractor
    module: features.clap
    params:
      model_id: "laion/larger_clap_general"
    short_name: CLAP
    benchmark_this: true 

  - name: AudioMAEExtractor
    module: features.audiomae
    params:
      model_id: "hance-ai/audiomae"
      trust_remote_code: true
    short_name: MAE
    benchmark_this: true 

  - name: EncodecExtractor
    module: features.encodec
    params:
      model_id: "facebook/encodec_24khz"
      bandwidth: 6.0
    short_name: CC
    benchmark_this: true 

  - name: WhisperEncoderExtractor_first_row
    base_extractor: WhisperEncoderExtractor
    averaging: first_row
    short_name: EWF
    benchmark_this: true 

  - name: WhisperEncoderExtractor_first_row_col
    base_extractor: WhisperEncoderExtractor
    averaging: first_row_col
    short_name: EWTF
    benchmark_this: true 

  - name: WhisperSegExtractor_first_row_col
    base_extractor: WhisperSegExtractor
    averaging: first_row_col
    short_name: ETF
    benchmark_this: true 

  - name: WhisperSegExtractor_first_row
    base_extractor: WhisperSegExtractor
    averaging: first_row
    short_name: EF
    benchmark_this: true 

  - name: WhisperSegExtractor_first_col
    base_extractor: WhisperSegExtractor
    averaging: first_col
    short_name: ET
    benchmark_this: true 

  - name: WhisperSegExtractor_first_row_col_pca_100
    base_extractor: WhisperSegExtractor
    averaging: first_row_col
    pca: 100
    pca_load_chunks: -1 
    short_name: ETF (D=100, PCA)
    benchmark_this: true 

  - name: WavLMExtractor_mean_time_pca_30
    base_extractor: WavLMExtractor
    pca: 30
    pca_load_chunks: -1
    short_name: WLM D30
    benchmark_this: true 

  - name: WavLMExtractor_mean_time_pca_100
    base_extractor: WavLMExtractor
    pca: 100
    pca_load_chunks: -1
    short_name: WLM D100
    benchmark_this: true 

  - name: Wav2Vec2Extractor_mean_time_pca_30
    base_extractor: Wav2Vec2Extractor
    pca: 30
    pca_load_chunks: -1
    short_name: W2V D30
    benchmark_this: true 

  - name: Wav2Vec2Extractor_mean_time_pca_100
    base_extractor: Wav2Vec2Extractor
    pca: 100
    pca_load_chunks: -1
    short_name: W2V D100
    benchmark_this: true 

  - name: CLAPExtractor_pca_30
    base_extractor: CLAPExtractor
    averaging: null
    pca: 30
    pca_load_chunks: -1
    short_name: CLP D30
    benchmark_this: true 

  - name: CLAPExtractor_pca_100
    base_extractor: CLAPExtractor
    averaging: null
    pca: 100
    pca_load_chunks: -1
    short_name: CLP D100
    benchmark_this: true 

  - name: AudioMAEExtractor_mean_time_dim_pca_30
    base_extractor: AudioMAEExtractor
    pca: 30
    pca_load_chunks: -1
    short_name: MAE D30
    benchmark_this: true 

  - name: AudioMAEExtractor_mean_time_dim_pca_100
    base_extractor: AudioMAEExtractor
    pca: 100
    pca_load_chunks: -1
    short_name: MAE D100
    benchmark_this: true

distances: 

  - name: cosine
    params:
      use_torchmetrics: true
      zero_diagonal: true 

  - name: euclidean
    params:
      use_torchmetrics: true
      zero_diagonal: true 

  - name: spearman
    params:
      use_gpu_if_available: true

benchmarks: 

  - name: PerceptualAlignment
    module: benchmarks.perceptual
    params:
      probe_csv_path: "${CODE_DIR}/vocsim/data/avian_perception/probes.csv"
      triplet_csv_path: "${CODE_DIR}/vocsim/data/avian_perception/triplets.csv"
      probe_consistency_threshold: 0.7
      bootstrap_ci: true
      n_bootstraps: 1000

extraction_batch_size: 512 
distance_gpu_block_size: 1024 