
project_root: "."
results_dir: "d:/data2/vocsim/results/paper_mouse_identity"
output_tables_dir: "d:/data2/vocsim/paper_outputs/mouse_identity_tables_generated"
features_dir: "d:/data2/vocsim/features/paper_mouse_identity"
models_dir: "d:/data2/vocsim/mouse_identity_models"
run_id: "mouse_identity_${now:%Y%m%d_%H%M%S}"
force_cpu: false
target_sample_rate: 250000 
feature_chunk_size_gb: 3 
logging:
  level: INFO

dataset:
  id: anonymous-submission000/vocsim-applications-mouse-identity
  subset: null
  split: train
  subsets_to_run: [mouse_identity]

train: []  

feature_extractors:

  - name: WhisperEncoderExtractor
    module: features.whisper
    params:
      model_id: "openai/whisper-large-v3"
    benchmark_this: false
    short_name: EW-Raw

  - name: WhisperEncoderExtractor_first_col_pca_10
    base_extractor: WhisperEncoderExtractor
    averaging: first_col
    pca: 10
    pca_load_chunks: -1
    benchmark_this: true
    short_name: EF (D=10)

  - name: WhisperEncoderExtractor_first_col_pca_30
    base_extractor: WhisperEncoderExtractor
    averaging: first_col
    pca: 30
    pca_load_chunks: -1
    benchmark_this: true
    short_name: EF (D=30)

  - name: WhisperEncoderExtractor_first_col_pca_100
    base_extractor: WhisperEncoderExtractor
    averaging: first_col
    pca: 100
    pca_load_chunks: -1
    benchmark_this: true
    short_name: EF (D=100)

  - name: WhisperEncoderExtractor_first_row_pca_10
    base_extractor: WhisperEncoderExtractor
    averaging: first_row
    pca: 10
    pca_load_chunks: -1
    benchmark_this: true
    short_name: ET (D=10)

  - name: WhisperEncoderExtractor_first_row_pca_30
    base_extractor: WhisperEncoderExtractor
    averaging: first_row
    pca: 30
    pca_load_chunks: -1
    benchmark_this: true
    short_name: ET (D=30)

  - name: WhisperEncoderExtractor_first_row_pca_100
    base_extractor: WhisperEncoderExtractor
    averaging: first_row
    pca: 100
    pca_load_chunks: -1
    benchmark_this: true
    short_name: ET (D=100)

  - name: WhisperEncoderExtractor_mean_row_col_pca_10
    base_extractor: WhisperEncoderExtractor
    averaging: mean_row_col
    pca: 10
    pca_load_chunks: -1
    benchmark_this: true
    short_name: EMTF (D=10)

  - name: WhisperEncoderExtractor_mean_row_col_pca_30
    base_extractor: WhisperEncoderExtractor
    averaging: mean_row_col
    pca: 30
    pca_load_chunks: -1
    benchmark_this: true
    short_name: EMTF (D=30)

  - name: WhisperEncoderExtractor_mean_row_col_pca_100
    base_extractor: WhisperEncoderExtractor
    averaging: mean_row_col
    pca: 100
    pca_load_chunks: -1
    benchmark_this: true
    short_name: EMTF (D=100)

  - name: WhisperEncoderExtractor_first_row_col_pca_10
    base_extractor: WhisperEncoderExtractor
    averaging: first_row_col
    pca: 10
    pca_load_chunks: -1
    benchmark_this: true
    short_name: ETF (D=10)

  - name: WhisperEncoderExtractor_first_row_col_pca_30
    base_extractor: WhisperEncoderExtractor
    averaging: first_row_col
    pca: 30
    pca_load_chunks: -1
    benchmark_this: true
    short_name: ETF (D=30)

  - name: WhisperEncoderExtractor_first_row_col_pca_100
    base_extractor: WhisperEncoderExtractor
    averaging: first_row_col
    pca: 100
    pca_load_chunks: -1
    benchmark_this: true
    short_name: ETF (D=100)

distances: []  
benchmarks:

  - name: ClassificationBenchmark
    module: benchmarks.classification
    params:
      n_splits: 5
      random_state: 42
      classifiers: ["mlp"]
      label_source_key: speaker
      eval_metrics: ["accuracy"]
      top_k: 5
      classifier_params:
        mlp:
          alpha: [0.01, 0.001, 0.0001]
          hidden_layer_sizes: [[400], [200, 200]]
          batch_size: [256]
          random_state: [42]
          max_iter: [10000]

extraction_batch_size: 32  
distance_gpu_block_size: 1024 